# Generated by Django 5.0.3 on 2024-03-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='languages',
            new_name='programming_languages',
        ),
    ]
